default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgres
  password: Rails.application.credentials.database_password
  host: localhost

development:
  <<: *default
  database: myappdb

test:
  <<: *default
  database: myappdb_test

# Store production database in the storage/ directory, which by default
# is mounted as a persistent Docker volume in config/deploy.yml.
production:
  primary:
    <<: *default
    database: myappdb_production
